//成功
pub const UPLOAD_USER_PROFILE_PHOTO_URL_SUCCESS: u32 = 0;
//默认失败
pub const UPLOAD_USER_PROFILE_PHOTO_URL_DEFAULT_FAILED: u32 = 1;
//上传数据库失败
pub const UPLOAD_USER_PROFILE_PHOTO_URL_TO_DB_FAILED: u32 = 2;
//失败
pub const UPLOAD_USER_PROFILE_PHOTO_URL_FAILED: u32 = 3;